services:
  duo-auth-proxy:
    image: oliverl21/duo-auth-proxy
    container_name: duo-authproxy
    restart: always
    volumes:
      - ./log:/opt/duoauthproxy/log
      - ./conf/authproxy.cfg:/opt/duoauthproxy/conf/authproxy.cfg
      - ./etc/duoauthproxy:/etc/duoauthproxy
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    networks:
      - duoproxy
    secrets:
      - duo_enrollment_key

secrets:
  duo_enrollment_key:
    file: ./duo_enrollment.key

networks:
  duoproxy:
