name: Build Multi-arch Image

on:
  workflow_dispatch:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0"
  push:
    paths-ignore:
      - "**.md"
      - ".github/**"

jobs:
  build:
    name: Build image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: version
        name: "Set DUO APP Version env"
        run: |
          echo "version=$(curl https://dl.duosecurity.com/authproxy_version.json | jq -r '.releases | keys | max')" >> $GITHUB_OUTPUT
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.io
      - name: Build and Push Image Debian
        uses: docker/build-push-action@v6
        with:
          tags: oliverl21/duo-auth-proxy:${{ steps.version.outputs.version }}-${{ github.sha }}-${{ matrix.platform }}
          file: ./dockerfile-debian
          platforms: linux/${{ matrix.platform }}
          push: true
          cache-from: type=gha,scope=debian-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=debian-${{ matrix.platform }}
          build-args: |
            DUOVERSION=${{ steps.version.outputs.version }}
      - name: Build and Push Image Alma
        uses: docker/build-push-action@v6
        with:
          tags: oliverl21/duo-auth-proxy:${{ steps.version.outputs.version }}-alma-${{ github.sha }}-${{ matrix.platform }}
          file: ./dockerfile-alma
          platforms: linux/${{ matrix.platform }}
          push: true
          cache-from: type=gha,scope=alma-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=alma-${{ matrix.platform }}
          build-args: |
            DUOVERSION=${{ steps.version.outputs.version }}

  create-manifests:
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
      - name: "Set current date as env variable"
        run: |
          echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        id: date # this is used on variable path
        
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.io

      - name: Create SHA manifest and push
        run: |
          docker buildx imagetools create -t \
            oliverl21/duo-auth-proxy:${{ needs.build.outputs.version }}-${{ steps.date.outputs.builddate}} -t \
            oliverl21/duo-auth-proxy:latest \
            oliverl21/duo-auth-proxy:${{ needs.build.outputs.version }}-${{ github.sha }}-amd64 \
            oliverl21/duo-auth-proxy:${{ needs.build.outputs.version }}-${{ github.sha }}-arm64


